package user

/*
 * File: internal/domains/user/model.go
 *
 * Purpose: data modeling for user management tasks
 *
 * License:
 *  See LICENSE.md for full license
 *  Copyright 2026 Part of the Tournabyte project
 *
 */

import (
	"time"

	"github.com/alexedwards/argon2id"
	"github.com/emvi/iso-639-1"
	"github.com/gin-gonic/gin"
	"go.mongodb.org/mongo-driver/v2/bson"
)

// Type `FullAccountDetails` represents the full account details of an authorized user on the Tournabyte platform
//
// Fields:
//   - ID: the user ID of this account (typically generated by mongodb as a document insert)
//   - Credentials: the login credentials of this account
//   - PrimaryProfile: the profile scaffold of this account
//   - Sessions: the list of active sessions (authenticated) by this account
//   - CreatedAt: the timestamp the account was created at
//   - UpdatedAt: the timestamp the account was updated at
type FullAccountDetails struct {
	ID             bson.ObjectID    `bson:"_id"`
	Credentials    LoginCredentials `bson:"login_credentials"`
	PrimaryProfile PlayerProfile    `bson:"primary_profile"`
	Sessions       []ActiveSession  `bson:"active_sessions"`
	CreatedAt      time.Time        `bson:"created_at"`
	UpdatedAt      time.Time        `bson:"updated_at"`
}

func NewAccountFromRequest(ctx *gin.Context, email string, displayName string, password string) FullAccountDetails {
	var account FullAccountDetails

	account.ID = bson.NewObjectID()
	account.CreatedAt = time.Now().UTC()
	account.UpdatedAt = account.CreatedAt
	account.Credentials = SecureCredentialsInRequest(ctx, email, password)
	account.PrimaryProfile = PopulateProfileInRequest(ctx, displayName)

	return account
}

// Type `LoginCredentials` stores the unique email and passphrase for an account
//
// Fields:
//   - Email: the user login of an account
//   - PasswordHash: the hashed password the user authenticates with
type LoginCredentials struct {
	Email        string `bson:"email"`
	PasswordHash string `bson:"password_hash"`
}

func SecureCredentialsInRequest(ctx *gin.Context, loginID string, loginKey string) LoginCredentials {
	var creds LoginCredentials
	hash, err := argon2id.CreateHash(loginKey, argon2id.DefaultParams)
	if err != nil {
		ctx.Error(err)
	}

	creds.Email = loginID
	creds.PasswordHash = hash
	return creds
}

// Type `ActiveSession` stores the refresh token information needed to reauthenticate without user intervention
//
// Fields:
//   - TokenHash: the hashed refresh token to compare against
//   - NotValidBefore: the timestamp when the refresh token becomes valid (typically the creation time)
//   - NotValidAfter: the timestamp when the refresh token becomes invalid (typically the expiration time)
type ActiveSession struct {
	TokenHash      string    `bson:"token_hash"`
	NotValidBefore time.Time `bson:"not_valid_before"`
	NotValidAfter  time.Time `bson:"not_valid_after"`
}

func SecureSessionToken(ctx *gin.Context, raw string) ActiveSession {
	issueTime := time.Now().UTC()
	hash, err := argon2id.CreateHash(raw, argon2id.DefaultParams)
	if err != nil {
		ctx.Error(err)
	}

	return ActiveSession{
		TokenHash:      hash,
		NotValidBefore: issueTime,
		NotValidAfter:  issueTime.Add(72 * time.Hour),
	}
}

// Type `ProfileSettings` stores the language and timezone preferences of an account
//
// Fields:
//   - Language: the language code specifying the language localization for this account
//   - Timezone: the timezone code specifying the time localization for this account
type ProfileSettings struct {
	Language string `bson:"language"`
	Timezone string `bson:"timezone"`
}

func DefaultProfileSettings() ProfileSettings {
	return ProfileSettings{
		Language: iso6391.CodeForName("English"),
		Timezone: time.UTC.String(),
	}
}

// Type `DefaultProfile` stores the default profile information used to create a profile when joining an organization or event
//
// Fields:
//   - DisplayName: the identifier used throughout the user interfaces for an account
//   - AvatarObjectKey: the object key for the default avatar used throughoout the user interfaces for an account
//   - Bio: the default bio string used throughout the user interfaces for an account
type PlayerProfile struct {
	DisplayName     string          `bson:"display_name"`
	AvatarObjectKey string          `bson:"avatar_key"`
	Bio             string          `bson:"bio"`
	Preferences     ProfileSettings `bson:"preferences"`
	CreatedAt       time.Time       `bson:"created_at"`
	UpdatedAt       time.Time       `bson:"updated_at"`
	ClaimedBy       bson.ObjectID   `bson:"claimed_by,omitempty"`
}

func PopulateProfileInRequest(ctx *gin.Context, displayName string) PlayerProfile {
	var profile PlayerProfile

	profile.DisplayName = displayName
	profile.CreatedAt = time.Now().UTC()
	profile.UpdatedAt = profile.CreatedAt
	profile.Preferences = DefaultProfileSettings()

	return profile
}
