package user

/*
 * File: internal/domains/user/model.go
 *
 * Purpose: data modeling for user management tasks
 *
 * License:
 *  See LICENSE.md for full license
 *  Copyright 2026 Part of the Tournabyte project
 *
 */

import (
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
)

// Type `FullAccountDetails` represents the full account details of an authorized user on the Tournabyte platform
//
// Fields:
//   - ID: the user ID of this account (typically generated by mongodb as a document insert)
//   - Credentials: the login credentials of this account
//   - PrimaryProfile: the profile scaffold of this account
//   - Sessions: the list of active sessions (authenticated) by this account
//   - CreatedAt: the timestamp the account was created at
//   - UpdatedAt: the timestamp the account was updated at
type FullAccountDetails struct {
	ID             bson.ObjectID    `bson:"_id"`
	Credentials    LoginCredentials `bson:"login_credentials" validate:"required,dive"`
	PrimaryProfile PlayerProfile    `bson:"primary_profile" validate:"required,dive"`
	Sessions       []ActiveSession  `bson:"active_sessions"`
	CreatedAt      time.Time        `bson:"created_at" validate:"required,datetime"`
	UpdatedAt      time.Time        `bson:"updated_at" validate:"required,datetime"`
}

// Type `LoginCredentials` stores the unique email and passphrase for an account
//
// Fields:
//   - Email: the user login of an account
//   - PasswordHash: the hashed password the user authenticates with
type LoginCredentials struct {
	Email        string `bson:"email" validate:"required,email"`
	PasswordHash string `bson:"password_hash" validate:"required"`
}

// Type `ActiveSession` stores the refresh token information needed to reauthenticate without user intervention
//
// Fields:
//   - TokenHash: the hashed refresh token to compare against
//   - NotValidBefore: the timestamp when the refresh token becomes valid (typically the creation time)
//   - NotValidAfter: the timestamp when the refresh token becomes invalid (typically the expiration time)
type ActiveSession struct {
	TokenHash      string    `bson:"token_hash"`
	NotValidBefore time.Time `bson:"not_valid_before"`
	NotValidAfter  time.Time `bson:"not_valid_after"`
}

// Type `ProfileSettings` stores the language and timezone preferences of an account
//
// Fields:
//   - Language: the language code specifying the language localization for this account
//   - Timezone: the timezone code specifying the time localization for this account
type ProfileSettings struct {
	Language string `bson:"language" validate:"bcp47_language_tag"`
	Timezone string `bson:"timezone" validate:"timezone"`
}

// Type `DefaultProfile` stores the default profile information used to create a profile when joining an organization or event
//
// Fields:
//   - DisplayName: the identifier used throughout the user interfaces for an account
//   - AvatarObjectKey: the object key for the default avatar used throughoout the user interfaces for an account
//   - Bio: the default bio string used throughout the user interfaces for an account
type PlayerProfile struct {
	ID              string          `bson:"_id,omitempty" validate:"mongodb"`
	DisplayName     string          `bson:"display_name" validate:"required,alphanumericspace"`
	AvatarObjectKey string          `bson:"avatar_key" validate:"dirpath"`
	Bio             string          `bson:"bio"`
	Preferences     ProfileSettings `bson:"preferences" validate:"dive"`
	CreatedAt       time.Time       `bson:"created_at" validate:"required,datetime"`
	UpdatedAt       time.Time       `bson:"updated_at" validate:"required,datetime"`
	ClaimedBy       string          `bson:"claimed_by,omitempty" validate:"mongodb"`
}

// Type `NewUserRequest` represents the minimum details required to create a user account
//
// Fields:
//   - Email: the email of the new user
//   - Password: the password of the new user (to be cryptographically secured before storing)
//   - DisplayName: the public display name of the new user
type NewUserRequest struct {
	Email       string `json:"email" validate:"required,email"`
	Password    string `json:"password" validate:"required"`
	DisplayName string `json:"displayName" validate:"required,alphanumericspace"`
}

// Type `NewUserResponse` represents the response structure for newly created user accounts
//
// Fields:
//   - ID: the new user ID
type NewUserResponse struct {
	ID string `json:"id"`
}
