package handlerutil

/*
 * File: pkg/handlerutil/errors.go
 *
 * Purpose: modeling the errors presented by HTTP handlers instead of leaking service-level errors
 *
 * License:
 *  See LICENSE.md for full license
 *  Copyright 2026 Part of the Tournabyte project
 *
 */

import "net/http"

// Constant error messages to display when handler functions encouter a failure
const (
	failedToBindRequest       = "I don't understand what you are trying to tell me."
	failedToProcessRequest    = "I don't know what to do with what you've given me."
	failedToAuthorizeRequest  = "You don't appear to have permission to access that."
	failedToReachUpstreamData = "I've having trouble reaching an operating partner."
	failedToRunWithoutIssue   = "I'm so dumb, I should just exec `$ rm -rf /`..."
)

var (
	ErrBadRequest          = handlerFailureFactory(http.StatusBadRequest, failedToBindRequest)
	ErrUnprocessibleEntity = handlerFailureFactory(http.StatusUnprocessableEntity, failedToProcessRequest)
	ErrNotAuthorized       = handlerFailureFactory(http.StatusUnauthorized, failedToAuthorizeRequest)
	ErrNoAccess            = handlerFailureFactory(http.StatusForbidden, failedToAuthorizeRequest)
	ErrUpstreamUnreachable = handlerFailureFactory(http.StatusBadGateway, failedToReachUpstreamData)
	ErrInternalServerError = handlerFailureFactory(http.StatusInternalServerError, failedToRunWithoutIssue)
)

// Type `handlerFailureFormatter` utilizes predicate-based matching rules to format errors as `handlerFailure` instances
//
// Members
//   - rules: matching predicates that determine if a given error coincides with a specific handler failure structure
//   - fallback: a last resort "catch-all" to convert the given error to a `handlerFailure` is not rules were satisfied
type handlerFailureFormatter struct {
	rules    []func(error) (error, bool)
	fallback func(...errorDetail) handlerFailure
}

// Function `FailureFormatter` creates a new `handlerFailureFormatter` instance with the given ruleset and a fallback of internal server error
//
// Parameters:
//   - ...rules: variadic length collection of rules this formatter should follow
//
// Returns:
//   - `handlerFailureFormatter`: the formatter to translate arbitrary errors into structured handler failures
func FailureFormatter(rules ...func(error) (error, bool)) handlerFailureFormatter {
	return handlerFailureFormatter{
		rules:    rules,
		fallback: ErrInternalServerError,
	}
}

// Type `(*handlerFailureFormatter).Format` takes the given error and translates it into a `handlerFailure` instance
//
// Parameters:
//   - err: the given error to try to wrap
//
// Returns:
//   - `error`: a wrapped error that statisfies `errors.Is(handlerFailure)`
func (fmt *handlerFailureFormatter) Format(err error) error {
	for _, rule := range fmt.rules {
		if wrapped, isWrapped := rule(err); isWrapped {
			return wrapped
		}
	}

	return fmt.fallback()
}

// Type `errorDetail` represents a detailed piece of information that is associated with a handler level failure
//
// Members:
//   - name: the shorthand indicator for the issue this detail represents
//   - info: the longform expression for the issue this detail represents
type errorDetail struct {
	name string
	info string
}

// Function `NewDetail` creates an `errorDetail` instance corresponding to the given name and info components
//
// Parameters:
//   - detailName: the name component of the newly created detail
//   - detailInfo: the info component of the newly created detail
//
// Returns:
//   - `errorDetail`: the newly created instance
func NewDetail(detailName string, detailInfo string) errorDetail {
	return errorDetail{
		name: detailName,
		info: detailInfo,
	}
}

// Type `handlerFailure` represents the `error` response portion that can be generated by an HTTP handler
//
// Members:
//   - statusCode: the HTTP status code that is associated with the failure
//   - errmsg: the top-level issue that was encountered during handler execution
//   - details: additional information regarding the failure
type handlerFailure struct {
	statusCode int
	Message    string
	Details    []errorDetail
}

// Function `handlerFailure.Error` implements the error interface for the handlerFailure type
func (f handlerFailure) Error() string {
	return f.Message
}

// Function `(*handlerFailure).DetailMapping` creates a name->info mapping of this details associated with this failure
//
// Returns:
//   - `map[string]string` mapping of detail name to associated detail information
func (f *handlerFailure) DetailMapping() map[string]string {
	if len(f.Details) == 0 {
		return nil
	}

	m := make(map[string]string)

	for _, d := range f.Details {
		m[d.name] = d.info
	}

	return m
}

// Function `handlerFailureFactory` creates a shorthand handler failure constructor with a predefined status code and error message, but allows details to be optionally included
//
// Parameters:
//   - code: the status code to include
//   - msg: the error message to include
//
// Returns:
//   - `func(details ...errorDetail) handlerFailure`: the shorthand constructor that allows additional details to be included
func handlerFailureFactory(code int, msg string) func(details ...errorDetail) handlerFailure {
	return func(details ...errorDetail) handlerFailure {
		return handlerFailure{
			statusCode: code,
			Message:    msg,
			Details:    details,
		}
	}
}
