services:
  mongodb01:
    image: mongo:8.2-rc
    command: --config /etc/mongo/mongod01.conf
    hostname: mongodb01.tournabyte.com
    restart: no
    ports:
      - 27017:27017
    volumes:
      - ./etc:/etc/mongo:ro
      - db_disk_01:/data/db
    secrets:
      - mongodb01_root_user
      - mongodb01_root_pass
      - mongo_cluster_keyfile
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb01_root_pass
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb01_root_user
  mongodb02:
    image: mongo:8.2-rc
    hostname: mongodb02.tournabyte.com
    command: --config /etc/mongo/mongod02.conf
    restart: no
    ports:
      - 27018:27017
    volumes:
      - ./etc:/etc/mongo:ro
      - db_disk_02:/data/db
    secrets:
      - mongodb02_root_user
      - mongodb02_root_pass
      - mongo_cluster_keyfile
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb02_root_pass
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb02_root_user
  mongodb03:
    image: mongo:8.2-rc
    hostname: mongodb03.tournabyte.com
    command: --config /etc/mongo/mongod03.conf
    restart: no
    ports:
      - 27019:27017
    volumes:
      - ./etc:/etc/mongo:ro
      - db_disk_03:/data/db
    secrets:
      - mongodb03_root_user
      - mongodb03_root_pass
      - mongo_cluster_keyfile
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb03_root_pass
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb03_root_user
  tbyte-devS3:
    image: quay.io/minio/minio
    restart: no
    command: server --console-address :9001 /data
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - s3_data:/data
    secrets:
      - minio_root_user
      - minio_root_pass
    environment:
      MINIO_ROOT_USER_FILE: /run/secrets/minio_root_user
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_root_pass
  tbyte-apiserver:
    depends_on:
      - tbyte-devS3
      - mongodb03
      - mongodb02
      - mongodb01
    hostname: api.tournabyte.com
    build:
      context: ..
      dockerfile: Dockerfile
      tags:
        - dev
        - preview
    restart: no
    ports:
      - 8080:3000
    secrets:
      - token_signing_key
      - mongo_password
      - minio_access_id
      - minio_access_key
      - tls_certificate
      - tls_keychain
volumes:
  db_disk_03:
  db_disk_02:
  db_disk_01:
  s3_data:
secrets:
  mongo_cluster_keyfile:
    file: ./.env/DBSHARD_KEYFILE.txt
  mongodb01_root_user:
    file: ./.env/DBROOT01_USERNAME.txt
  mongodb01_root_pass:
    file: ./.env/DBROOT01_PASSWORD.txt
  mongodb02_root_user:
    file: ./.env/DBROOT02_USERNAME.txt
  mongodb02_root_pass:
    file: ./.env/DBROOT02_PASSWORD.txt
  mongodb03_root_user:
    file: ./.env/DBROOT03_USERNAME.txt
  mongodb03_root_pass:
    file: ./.env/DBROOT03_PASSWORD.txt
  minio_root_user:
    file: ./.env/S3ROOT_USERNAME.txt
  minio_root_pass:
    file: ./.env/S3ROOT_PASSWORD.txt
  token_signing_key:
    file: ./.env/JWT_SECRET_KEY.txt
  mongo_password:
    file: ./.env/DBROOT01_PASSWORD.txt
  minio_access_id:
    file: ./.env/S3ROOT_USERNAME.txt
  minio_access_key:
    file: ./.env/S3ROOT_PASSWORD.txt
  tls_keychain:
    file: ./.env/TLS_KEYCHAIN.txt
  tls_certificate:
    file: ./.env/TLS_CERTIFICATE.txt
